<?php
// Metas
$this->headMeta()->appendName('X-UA-Compatible', 'IE=edge,chrome=1');
$this->headMeta()->appendName('viewport', 'width=device-width,initial-scale=1.0');
$this->headMeta()->appendName('description', '');
$this->headMeta()->appendName('keywords', '');

// DocType
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Zend Framework Quickstart Application</title>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/assets/css/screen.css')); ?>
    </head>
    <body>
        <div id="header">
            <div id="header-logo">
                <strong>ZF Quickstart Application</strong>
            </div>
            <div id="header-nav">
                <a href="<?php echo $this->url(array('controller' => 'index'), 'default', true); ?>" class="active">Main page</a> 
                <a href="<?php echo $this->url(array('controller' => 'guestbook'), 'default', true); ?>" class="button">Guestbook</a> 
            </div>
        </div>

        <div id="container">
            <?php echo $this->layout()->content ?>
        </div>
    </body>
</html>
